title: Sai Amrit Patnaik
author: Sai Amrit Patnaik
email: patnaiksai1234@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi !! I am Sai Amrit Patnaik a final yer undergraduae from iiit bhubaneswar. I work in the field of 
  machine learning and deep learning.

# social links
twitter_username: saiamritpatnaik
github_username:  saiamrit

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
